class AllahName {
  final int number;
  final String arabic;
  final String transliteration;
  final String meaningAr;
  final String meaningEn;
  const AllahName({
    required this.number,
    required this.arabic,
    required this.transliteration,
    required this.meaningAr,
    required this.meaningEn,
  });
}

const List<AllahName> allahNames = [
  AllahName(number: 1, arabic: 'الرَّحْمَنُ', transliteration: 'Ar-Rahman', meaningAr: 'الذي وسعت رحمته كل شيء', meaningEn: 'The Most Compassionate'),
  AllahName(number: 2, arabic: 'الرَّحِيمُ', transliteration: 'Ar-Raheem', meaningAr: 'الذي يرحم المؤمنين خاصة', meaningEn: 'The Most Merciful'),
  AllahName(number: 3, arabic: 'الْمَلِكُ', transliteration: 'Al-Malik', meaningAr: 'المالك المتصرف في ملكه', meaningEn: 'The King'),
  AllahName(number: 4, arabic: 'الْقُدُّوسُ', transliteration: 'Al-Quddus', meaningAr: 'المنزه عن كل عيب ونقص', meaningEn: 'The Most Holy'),
  AllahName(number: 5, arabic: 'السَّلَامُ', transliteration: 'As-Salam', meaningAr: 'السالم من كل عيب', meaningEn: 'The Source of Peace'),
  AllahName(number: 6, arabic: 'الْمُؤْمِنُ', transliteration: 'Al-Mu\'min', meaningAr: 'المصدق لرسله بالمعجزات', meaningEn: 'The Granter of Security'),
  AllahName(number: 7, arabic: 'الْمُهَيْمِنُ', transliteration: 'Al-Muhaymin', meaningAr: 'الرقيب على كل شيء', meaningEn: 'The Guardian'),
  AllahName(number: 8, arabic: 'الْعَزِيزُ', transliteration: 'Al-Aziz', meaningAr: 'الغالب الذي لا يُغلَب', meaningEn: 'The Almighty'),
  AllahName(number: 9, arabic: 'الْجَبَّارُ', transliteration: 'Al-Jabbar', meaningAr: 'الذي يجبر الكسير ويغني الفقير', meaningEn: 'The Compeller'),
  AllahName(number: 10, arabic: 'الْمُتَكَبِّرُ', transliteration: 'Al-Mutakabbir', meaningAr: 'المتعالي عن صفات الخلق', meaningEn: 'The Supreme'),
  AllahName(number: 11, arabic: 'الْخَالِقُ', transliteration: 'Al-Khaliq', meaningAr: 'المبدع للخلق على غير مثال', meaningEn: 'The Creator'),
  AllahName(number: 12, arabic: 'الْبَارِئُ', transliteration: 'Al-Bari\'', meaningAr: 'المُنشئ للخلق بريئًا من التفاوت', meaningEn: 'The Originator'),
  AllahName(number: 13, arabic: 'الْمُصَوِّرُ', transliteration: 'Al-Musawwir', meaningAr: 'الذي صوّر الخلق وأحسن صورهم', meaningEn: 'The Fashioner'),
  AllahName(number: 14, arabic: 'الْغَفَّارُ', transliteration: 'Al-Ghaffar', meaningAr: 'كثير المغفرة لعباده', meaningEn: 'The All-Forgiving'),
  AllahName(number: 15, arabic: 'الْقَهَّارُ', transliteration: 'Al-Qahhar', meaningAr: 'القاهر لكل شيء', meaningEn: 'The Subduer'),
  AllahName(number: 16, arabic: 'الْوَهَّابُ', transliteration: 'Al-Wahhab', meaningAr: 'كثير العطاء بلا مقابل', meaningEn: 'The Bestower'),
  AllahName(number: 17, arabic: 'الرَّزَّاقُ', transliteration: 'Ar-Razzaq', meaningAr: 'الذي يرزق كل مخلوق', meaningEn: 'The Provider'),
  AllahName(number: 18, arabic: 'الْفَتَّاحُ', transliteration: 'Al-Fattah', meaningAr: 'الذي يفتح المغلق وييسر العسير', meaningEn: 'The Opener'),
  AllahName(number: 19, arabic: 'الْعَلِيمُ', transliteration: 'Al-Alim', meaningAr: 'المحيط علمه بكل شيء', meaningEn: 'The All-Knowing'),
  AllahName(number: 20, arabic: 'الْقَابِضُ', transliteration: 'Al-Qabid', meaningAr: 'الذي يقبض الرزق بحكمته', meaningEn: 'The Withholder'),
  AllahName(number: 21, arabic: 'الْبَاسِطُ', transliteration: 'Al-Basit', meaningAr: 'الذي يبسط الرزق لمن يشاء', meaningEn: 'The Extender'),
  AllahName(number: 22, arabic: 'الْخَافِضُ', transliteration: 'Al-Khafid', meaningAr: 'الذي يخفض المتكبرين', meaningEn: 'The Abaser'),
  AllahName(number: 23, arabic: 'الرَّافِعُ', transliteration: 'Ar-Rafi\'', meaningAr: 'الذي يرفع أوليائه', meaningEn: 'The Exalter'),
  AllahName(number: 24, arabic: 'الْمُعِزُّ', transliteration: 'Al-Mu\'izz', meaningAr: 'الذي يُعز من يشاء', meaningEn: 'The Honourer'),
  AllahName(number: 25, arabic: 'الْمُذِلُّ', transliteration: 'Al-Mudhill', meaningAr: 'الذي يُذل من يشاء بعدله', meaningEn: 'The Dishonourer'),
  AllahName(number: 26, arabic: 'السَّمِيعُ', transliteration: 'As-Sami\'', meaningAr: 'الذي يسمع كل شيء', meaningEn: 'The All-Hearing'),
  AllahName(number: 27, arabic: 'الْبَصِيرُ', transliteration: 'Al-Basir', meaningAr: 'الذي يرى كل شيء', meaningEn: 'The All-Seeing'),
  AllahName(number: 28, arabic: 'الْحَكَمُ', transliteration: 'Al-Hakam', meaningAr: 'الذي يحكم بالحق', meaningEn: 'The Judge'),
  AllahName(number: 29, arabic: 'الْعَدْلُ', transliteration: 'Al-\'Adl', meaningAr: 'الذي لا يجور في حكمه', meaningEn: 'The Utterly Just'),
  AllahName(number: 30, arabic: 'اللَّطِيفُ', transliteration: 'Al-Latif', meaningAr: 'اللطيف بعباده الخبير بهم', meaningEn: 'The Subtle One'),
  AllahName(number: 31, arabic: 'الْخَبِيرُ', transliteration: 'Al-Khabir', meaningAr: 'العالم ببواطن الأمور', meaningEn: 'The All-Aware'),
  AllahName(number: 32, arabic: 'الْحَلِيمُ', transliteration: 'Al-Halim', meaningAr: 'الذي لا يعجل بالعقوبة', meaningEn: 'The Most Forbearing'),
  AllahName(number: 33, arabic: 'الْعَظِيمُ', transliteration: 'Al-\'Adheem', meaningAr: 'ذو العظمة في ذاته وصفاته', meaningEn: 'The Magnificent'),
  AllahName(number: 34, arabic: 'الْغَفُورُ', transliteration: 'Al-Ghafur', meaningAr: 'الذي يغفر الذنوب جميعًا', meaningEn: 'The All-Forgiving'),
  AllahName(number: 35, arabic: 'الشَّكُورُ', transliteration: 'Ash-Shakur', meaningAr: 'الذي يجزي على القليل بالكثير', meaningEn: 'The Most Appreciative'),
  AllahName(number: 36, arabic: 'الْعَلِيُّ', transliteration: 'Al-\'Ali', meaningAr: 'المرتفع فوق كل شيء', meaningEn: 'The Most High'),
  AllahName(number: 37, arabic: 'الْكَبِيرُ', transliteration: 'Al-Kabir', meaningAr: 'الذي كل شيء دونه صغير', meaningEn: 'The Most Great'),
  AllahName(number: 38, arabic: 'الْحَفِيظُ', transliteration: 'Al-Hafidh', meaningAr: 'الحافظ لخلقه وأعمالهم', meaningEn: 'The Preserver'),
  AllahName(number: 39, arabic: 'الْمُقِيتُ', transliteration: 'Al-Muqit', meaningAr: 'الذي يخلق الأقوات ويوصلها', meaningEn: 'The Sustainer'),
  AllahName(number: 40, arabic: 'الْحَسِيبُ', transliteration: 'Al-Hasib', meaningAr: 'الذي يحاسب عباده على أعمالهم', meaningEn: 'The Reckoner'),
  AllahName(number: 41, arabic: 'الْجَلِيلُ', transliteration: 'Al-Jalil', meaningAr: 'ذو الجلال والعظمة', meaningEn: 'The Majestic'),
  AllahName(number: 42, arabic: 'الْكَرِيمُ', transliteration: 'Al-Karim', meaningAr: 'كثير الخير عظيم العطاء', meaningEn: 'The Most Generous'),
  AllahName(number: 43, arabic: 'الرَّقِيبُ', transliteration: 'Ar-Raqib', meaningAr: 'المراقب لأحوال خلقه', meaningEn: 'The Watchful'),
  AllahName(number: 44, arabic: 'الْمُجِيبُ', transliteration: 'Al-Mujib', meaningAr: 'الذي يجيب دعاء الداعين', meaningEn: 'The Responsive'),
  AllahName(number: 45, arabic: 'الْوَاسِعُ', transliteration: 'Al-Wasi\'', meaningAr: 'الواسع في علمه ورحمته', meaningEn: 'The All-Encompassing'),
  AllahName(number: 46, arabic: 'الْحَكِيمُ', transliteration: 'Al-Hakim', meaningAr: 'الذي أحكم خلقه وأتقن صنعه', meaningEn: 'The All-Wise'),
  AllahName(number: 47, arabic: 'الْوَدُودُ', transliteration: 'Al-Wadud', meaningAr: 'المحب لأوليائه الصالحين', meaningEn: 'The Most Loving'),
  AllahName(number: 48, arabic: 'الْمَجِيدُ', transliteration: 'Al-Majid', meaningAr: 'ذو الشرف والعز والكرم', meaningEn: 'The Most Glorious'),
  AllahName(number: 49, arabic: 'الْبَاعِثُ', transliteration: 'Al-Ba\'ith', meaningAr: 'الذي يبعث الخلق يوم القيامة', meaningEn: 'The Resurrector'),
  AllahName(number: 50, arabic: 'الشَّهِيدُ', transliteration: 'Ash-Shahid', meaningAr: 'الشاهد على كل شيء', meaningEn: 'The All-Witnessing'),
  AllahName(number: 51, arabic: 'الْحَقُّ', transliteration: 'Al-Haqq', meaningAr: 'الثابت الذي لا يزول', meaningEn: 'The Absolute Truth'),
  AllahName(number: 52, arabic: 'الْوَكِيلُ', transliteration: 'Al-Wakil', meaningAr: 'القائم بمصالح عباده', meaningEn: 'The Trustee'),
  AllahName(number: 53, arabic: 'الْقَوِيُّ', transliteration: 'Al-Qawiyy', meaningAr: 'ذو القوة المتين', meaningEn: 'The All-Strong'),
  AllahName(number: 54, arabic: 'الْمَتِينُ', transliteration: 'Al-Matin', meaningAr: 'الشديد الذي لا تنقطع قوته', meaningEn: 'The Firm'),
  AllahName(number: 55, arabic: 'الْوَلِيُّ', transliteration: 'Al-Waliyy', meaningAr: 'الناصر المتولي أمور عباده', meaningEn: 'The Protecting Friend'),
  AllahName(number: 56, arabic: 'الْحَمِيدُ', transliteration: 'Al-Hamid', meaningAr: 'المحمود على كل حال', meaningEn: 'The Praiseworthy'),
  AllahName(number: 57, arabic: 'الْمُحْصِي', transliteration: 'Al-Muhsi', meaningAr: 'الذي أحصى كل شيء عددًا', meaningEn: 'The Reckoner of All'),
  AllahName(number: 58, arabic: 'الْمُبْدِئُ', transliteration: 'Al-Mubdi\'', meaningAr: 'الذي بدأ الخلق وخلقهم ابتداءً', meaningEn: 'The Originator'),
  AllahName(number: 59, arabic: 'الْمُعِيدُ', transliteration: 'Al-Mu\'id', meaningAr: 'الذي يعيد الخلق بعد الفناء', meaningEn: 'The Restorer'),
  AllahName(number: 60, arabic: 'الْمُحْيِي', transliteration: 'Al-Muhyi', meaningAr: 'الذي يحيي الموتى', meaningEn: 'The Giver of Life'),
  AllahName(number: 61, arabic: 'الْمُمِيتُ', transliteration: 'Al-Mumit', meaningAr: 'الذي يقضي بالموت على من يشاء', meaningEn: 'The Bringer of Death'),
  AllahName(number: 62, arabic: 'الْحَيُّ', transliteration: 'Al-Hayy', meaningAr: 'الحي حياة أبدية لا يموت', meaningEn: 'The Ever-Living'),
  AllahName(number: 63, arabic: 'الْقَيُّومُ', transliteration: 'Al-Qayyum', meaningAr: 'القائم بنفسه المقيم لغيره', meaningEn: 'The Self-Subsisting'),
  AllahName(number: 64, arabic: 'الْوَاجِدُ', transliteration: 'Al-Wajid', meaningAr: 'الغني الذي لا يفقد شيئًا', meaningEn: 'The Perceiver'),
  AllahName(number: 65, arabic: 'الْمَاجِدُ', transliteration: 'Al-Majid', meaningAr: 'العظيم الكريم', meaningEn: 'The Noble'),
  AllahName(number: 66, arabic: 'الْوَاحِدُ', transliteration: 'Al-Wahid', meaningAr: 'المتوحد بالذات والصفات', meaningEn: 'The One'),
  AllahName(number: 67, arabic: 'الأَحَدُ', transliteration: 'Al-Ahad', meaningAr: 'الفرد الذي لا شريك له', meaningEn: 'The Unique'),
  AllahName(number: 68, arabic: 'الصَّمَدُ', transliteration: 'As-Samad', meaningAr: 'السيد الذي تصمد إليه الخلائق', meaningEn: 'The Eternal'),
  AllahName(number: 69, arabic: 'الْقَادِرُ', transliteration: 'Al-Qadir', meaningAr: 'القادر على كل شيء', meaningEn: 'The All-Capable'),
  AllahName(number: 70, arabic: 'الْمُقْتَدِرُ', transliteration: 'Al-Muqtadir', meaningAr: 'الذي ينفذ قدرته كيف يشاء', meaningEn: 'The Omnipotent'),
  AllahName(number: 71, arabic: 'الْمُقَدِّمُ', transliteration: 'Al-Muqaddim', meaningAr: 'الذي يقدم من يشاء من خلقه', meaningEn: 'The Expediter'),
  AllahName(number: 72, arabic: 'الْمُؤَخِّرُ', transliteration: 'Al-Mu\'akhkhir', meaningAr: 'الذي يؤخر ما يشاء', meaningEn: 'The Delayer'),
  AllahName(number: 73, arabic: 'الأَوَّلُ', transliteration: 'Al-Awwal', meaningAr: 'الأول الذي ليس قبله شيء', meaningEn: 'The First'),
  AllahName(number: 74, arabic: 'الآخِرُ', transliteration: 'Al-Akhir', meaningAr: 'الآخر الذي ليس بعده شيء', meaningEn: 'The Last'),
  AllahName(number: 75, arabic: 'الظَّاهِرُ', transliteration: 'Adh-Dhahir', meaningAr: 'الظاهر بأدلته فوق كل شيء', meaningEn: 'The Manifest'),
  AllahName(number: 76, arabic: 'الْبَاطِنُ', transliteration: 'Al-Batin', meaningAr: 'المحتجب عن أبصار الخلق', meaningEn: 'The Hidden'),
  AllahName(number: 77, arabic: 'الْوَالِي', transliteration: 'Al-Wali', meaningAr: 'المالك للأشياء المتصرف فيها', meaningEn: 'The Governor'),
  AllahName(number: 78, arabic: 'الْمُتَعَالِي', transliteration: 'Al-Muta\'ali', meaningAr: 'الذي جل شأنه عن كل نقص', meaningEn: 'The Most Exalted'),
  AllahName(number: 79, arabic: 'الْبَرُّ', transliteration: 'Al-Barr', meaningAr: 'المحسن إلى عباده', meaningEn: 'The Source of Goodness'),
  AllahName(number: 80, arabic: 'التَّوَّابُ', transliteration: 'At-Tawwab', meaningAr: 'الذي يقبل توبة التائبين', meaningEn: 'The Ever-Pardoning'),
  AllahName(number: 81, arabic: 'الْمُنْتَقِمُ', transliteration: 'Al-Muntaqim', meaningAr: 'الذي ينتقم من الظالمين', meaningEn: 'The Avenger'),
  AllahName(number: 82, arabic: 'الْعَفُوُّ', transliteration: 'Al-\'Afuww', meaningAr: 'الذي يعفو عن السيئات', meaningEn: 'The Pardoner'),
  AllahName(number: 83, arabic: 'الرَّءُوفُ', transliteration: 'Ar-Ra\'uf', meaningAr: 'شديد الرحمة بعباده', meaningEn: 'The Most Kind'),
  AllahName(number: 84, arabic: 'مَالِكُ الْمُلْكِ', transliteration: 'Malik al-Mulk', meaningAr: 'المتصرف في ملكه كيف يشاء', meaningEn: 'Master of the Kingdom'),
  AllahName(number: 85, arabic: 'ذُو الْجَلَالِ وَالْإِكْرَامِ', transliteration: 'Dhul-Jalali wal-Ikram', meaningAr: 'ذو العظمة والفضل', meaningEn: 'Lord of Majesty and Generosity'),
  AllahName(number: 86, arabic: 'الْمُقْسِطُ', transliteration: 'Al-Muqsit', meaningAr: 'العادل في حكمه', meaningEn: 'The Equitable'),
  AllahName(number: 87, arabic: 'الْجَامِعُ', transliteration: 'Al-Jami\'', meaningAr: 'الذي يجمع الخلائق يوم القيامة', meaningEn: 'The Gatherer'),
  AllahName(number: 88, arabic: 'الْغَنِيُّ', transliteration: 'Al-Ghaniyy', meaningAr: 'الغني عن كل شيء', meaningEn: 'The Self-Sufficient'),
  AllahName(number: 89, arabic: 'الْمُغْنِي', transliteration: 'Al-Mughni', meaningAr: 'الذي يغني من يشاء من خلقه', meaningEn: 'The Enricher'),
  AllahName(number: 90, arabic: 'الْمَانِعُ', transliteration: 'Al-Mani\'', meaningAr: 'الذي يمنع بحكمته ما يشاء', meaningEn: 'The Withholder'),
  AllahName(number: 91, arabic: 'الضَّارُّ', transliteration: 'Ad-Darr', meaningAr: 'الذي يضر من يشاء بحكمته', meaningEn: 'The Distresser'),
  AllahName(number: 92, arabic: 'النَّافِعُ', transliteration: 'An-Nafi\'', meaningAr: 'الذي ينفع من يشاء', meaningEn: 'The Benefactor'),
  AllahName(number: 93, arabic: 'النُّورُ', transliteration: 'An-Nur', meaningAr: 'منور السماوات والأرض', meaningEn: 'The Light'),
  AllahName(number: 94, arabic: 'الْهَادِي', transliteration: 'Al-Hadi', meaningAr: 'الذي يهدي عباده إلى الحق', meaningEn: 'The Guide'),
  AllahName(number: 95, arabic: 'الْبَدِيعُ', transliteration: 'Al-Badi\'', meaningAr: 'خالق الخلق على غير مثال', meaningEn: 'The Incomparable Originator'),
  AllahName(number: 96, arabic: 'الْبَاقِي', transliteration: 'Al-Baqi', meaningAr: 'الدائم الذي لا يفنى', meaningEn: 'The Everlasting'),
  AllahName(number: 97, arabic: 'الْوَارِثُ', transliteration: 'Al-Warith', meaningAr: 'الباقي بعد فناء الخلق', meaningEn: 'The Inheritor'),
  AllahName(number: 98, arabic: 'الرَّشِيدُ', transliteration: 'Ar-Rashid', meaningAr: 'الذي أفعاله على سنن الحكمة', meaningEn: 'The Guide to the Right Path'),
  AllahName(number: 99, arabic: 'الصَّبُورُ', transliteration: 'As-Sabur', meaningAr: 'الذي لا يعاجل العصاة بالعقوبة', meaningEn: 'The Most Patient'),
];
